#!/bin/bash
# =============================================================================
# Chat Archive — Build Script (Phase 2)
# =============================================================================
# Concatenates source files into content.js for the Chrome extension.
# No bundler needed — files are concatenated in dependency order inside an IIFE.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="$SCRIPT_DIR/content.js"

echo "Building Chat Archive content script (Phase 2)..."

cat > "$OUT" << 'BANNER'
// =============================================================================
// Chat Archive — Content Script (Built)
// =============================================================================
// Auto-generated by build.sh. Do not edit directly — edit files in src/ instead.
//
// Phase 2: Pass 0 clipboard extraction (all 5 platforms) + Pass 1 heuristics
//          + JSON & Markdown export
//
// Zero network. Zero telemetry. Conversations never leave your browser.
// =============================================================================

(function() {
'use strict';

BANNER

# Concatenate in dependency order:
# 1. Constants & shared utilities (no deps)
# 2. Platform extractors (depend on constants)
# 3. Heuristics (depends on constants)
# 4. Serializer (depends on constants)
# 5. File writer (depends on constants)
# 6. Content script orchestrator (depends on everything above)

FILES=(
  "src/utils/constants.js"
  "src/extractors/claude.js"
  "src/extractors/chatgpt.js"
  "src/extractors/gemini.js"
  "src/extractors/grok.js"
  "src/extractors/grok-x.js"
  "src/heuristics/pass1.js"
  "src/utils/serializer.js"
  "src/utils/filewriter.js"
  "src/content.js"
)

for file in "${FILES[@]}"; do
  filepath="$SCRIPT_DIR/$file"
  if [ ! -f "$filepath" ]; then
    echo "ERROR: Missing file: $filepath"
    exit 1
  fi
  echo "  + $file"
  echo "" >> "$OUT"
  echo "// --- $file ---" >> "$OUT"
  cat "$filepath" >> "$OUT"
  echo "" >> "$OUT"
done

# Close the IIFE
echo "})();" >> "$OUT"

BYTES=$(wc -c < "$OUT")
LINES=$(wc -l < "$OUT")
echo ""
echo "Built: $OUT"
echo "  Size: $BYTES bytes, $LINES lines"
echo "  Files: ${#FILES[@]} source files"
echo ""
echo "To load: chrome://extensions → Load unpacked → select $(dirname "$OUT")"
